name: flutter_themekit_plus
description: "A comprehensive Flutter theming system that provides a plug-and-play solution for creating consistent, dynamic, and accessible user interfaces. It supports light/dark/system modes, curated color palettes, auto theme switching, prebuilt themed widgets, context-aware theming, and modular theme extensions."
version: 0.0.2
homepage: https://github.com/santhosh-ceo/flutter_themekit_plus
repository: https://github.com/santhosh-ceo/flutter_themekit_plus
issue_tracker: https://github.com/santhosh-ceo/flutter_themekit_plus/issues

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  plugin_platform_interface: ^2.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


